---
title: "Enriched pathway analysis: fgsea"
date: "Created: 2021-01-28 Updated: `r Sys.Date()`"
author: 
  - name: "Hua Zou"
    email: "zouhua1@outlook.com"
output: 
  html_notebook:
    codes: hide
---

## Introduction

Performing Enriched pathway analysis via fgsea package

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(ggplot2)
library(data.table)
library(fgsea)
# library(tidyquant)

rm(list = ls())
options(stringsAsFactors = F)
options(future.globals.maxSize = 1000 * 1024^2)

grp <- c("S1", "S2")
grp.col <- c("#6C326C", "#77A2D1")
```


### load data 

* gene Expression DESeq2 object
```{r}
phen <- fread("../../Result/phenotype/phenotype_cluster.csv")
geneExp <- readRDS("../../Result/Differential/geneExp_Diff.RDS")

pathways_hallmark_all <- gmtPathways("../../Result/GeneID/msigdb.v7.1.symbols.gmt")
pathways_hallmark_kegg <- gmtPathways("../../Result/GeneID/msigdb.v7.1.symbols_KEGG.gmt")
pathways_hallmark_GO <- gmtPathways("../../Result/GeneID/msigdb.v7.1.symbols_GO.gmt")
```


### Curation Function 

the Genes were ranked by the **stat** index.
```{r}
get_fgsea <- function(dataset=geneExp$diff_res,
                      pathways=pathways_hallmark_kegg){
  
  # dataset=geneExp$diff_res
  # pathways=pathways_hallmark_kegg
  
  dat <- dataset %>% data.frame() %>%
    rownames_to_column("SYMBOL") %>%
    dplyr::select(SYMBOL, stat) %>% 
    na.omit() %>% 
    distinct() %>% 
    group_by(SYMBOL) %>% 
    summarize(stat=mean(stat))
  
  ranks <- deframe(dat)

  fgseaRes <- fgsea(pathways=pathways, 
                    stats=ranks, 
                    nperm=1000)
  
  pathways_gene <- pathways %>% 
                    enframe("pathway", "SYMBOL") %>% 
                    tidyr::unnest(cols = c(SYMBOL)) %>% 
                    inner_join(dataset %>% data.frame() %>% 
                                 rownames_to_column("SYMBOL"),
                               by="SYMBOL") 
  res <- list(ranks=ranks, fgres=fgseaRes, pgene=pathways_gene)
  
  return(res)
}

# barplot
get_plot <- function(dataset=kegg_gsea,
                     pathways=pathways_hallmark_kegg,
                     number=10,
                     tag="kegg"){

  # dataset=kegg_gsea
  # pathways=pathways_hallmark_kegg
  # number=10
  # tag="kegg"
  
  fgseaRes <- dataset$fgres
  ranks <- dataset$ranks

  topPathwaysUp <- fgseaRes[ES > 0][head(order(pval), n=number), pathway]
  topPathwaysDown <- fgseaRes[ES < 0][head(order(pval), n=number), pathway]
  topPathways <- c(topPathwaysUp, rev(topPathwaysDown))
  
  if(tag == "kegg"){
    names <- paste0("../../Result/figure/KEGG/KEGG_topPathway_", number, ".pdf")    
  }else{
    names <- paste0("../../Result/figure/GO/GO_topPathway_", number, ".pdf")    
  }

  pdf(file = names, width = 11, height = 10)
  plotGseaTable(pathways[topPathways], 
                ranks, 
                fgseaRes, 
                gseaParam=0.5)
  dev.off()
  
  
  fgseaResTidy <- fgseaRes %>%
    as_tibble() %>%
    filter(pathway%in%topPathways) %>%
    arrange(desc(NES))%>%
    mutate(color=ifelse(NES < 0, grp[1], grp[2]),
           color=factor(color, levels = grp))
  
 pl_bar <- ggplot(fgseaResTidy, aes(reorder(pathway, NES), NES))+
    geom_col(aes(fill = color))+
    coord_flip()+
    scale_fill_manual(values = grp.col)+
    labs(x="Pathway", y="Normalized Enrichment Score",
         title="Hallmark pathways NES from GSEA") + 
    guides(fill=guide_legend("Cluster"))+
    theme_minimal()+
    theme(axis.title = element_text(face = 'bold',color = 'black',size = 14),
                  axis.text = element_text(color = 'black',size = 10),
                  text = element_text(size = 8, color = "black", family="serif"),
                  legend.position = 'right',
                  legend.key.height = unit(0.6,'cm'),
                  legend.text = element_text(face = "bold", color = 'black',size = 10),
                  strip.text = element_text(face = "bold", size = 14))
 
 return(pl_bar)
}

# es per pathway 
get_es_plot <- function(dataset=kegg_gsea,
                     pathways=pathways_hallmark_kegg,
                     pathway_name="KEGG_REGULATION_OF_ACTIN_CYTOSKELETON"){

  # dataset=kegg_gsea
  # pathways=pathways_hallmark_kegg
  # pathway_name="KEGG_REGULATION_OF_ACTIN_CYTOSKELETON"  
  
  
  pl <- plotEnrichment(pathways[[pathway_name]], dataset$ranks)+
    labs(title=pathway_name,
         x="Rank in Ordered DataSet",
         y="Enrichment Score(ES)")+
    theme(axis.title = element_text(face = 'bold',color = 'black',size = 14),
                  axis.text = element_text(color = 'black',size = 10),
                  text = element_text(size = 8, color = "black", family="serif"),
                  legend.position = 'right',
                  legend.key.height = unit(0.6,'cm'),
                  legend.text = element_text(face = "bold", color = 'black',size = 10),
                  strip.text = element_text(face = "bold", size = 14)) 
  return(pl)
}
```


### KEGG 
```{r}
kegg_gsea <- get_fgsea(pathways = pathways_hallmark_kegg)

if(!dir.exists("../../Result/Enrichment")){
  dir.create("../../Result/Enrichment", recursive = T)
}
saveRDS(kegg_gsea, "../../Result/Enrichment/KEGG_pathway_gsea.RDS")
write.csv(kegg_gsea$pgene, "../../Result/Enrichment/KEGG_pathway_gsea_gene.csv", row.names = F)

# plot per pathway 
if(!dir.exists("../../Result/figure/KEGG")){
  dir.create("../../Result/figure/KEGG", recursive = T)
}

KEGG_REGULATION_OF_ACTIN_CYTOSKELETON_pl <- 
  get_es_plot(dataset=kegg_gsea, pathways=pathways_hallmark_kegg,
         pathway_name="KEGG_REGULATION_OF_ACTIN_CYTOSKELETON")
KEGG_REGULATION_OF_ACTIN_CYTOSKELETON_pl
ggsave("../../Result/figure/KEGG/KEGG_REGULATION_OF_ACTIN_CYTOSKELETON.pdf",
       KEGG_REGULATION_OF_ACTIN_CYTOSKELETON_pl, width = 5, height = 4, dpi = 600)

# top pathway
kegg_bar <- get_plot(dataset=kegg_gsea, pathways=pathways_hallmark_kegg, number=10, tag="kegg")
kegg_bar
ggsave("../../Result/figure/KEGG/KEGG_barplot.pdf", kegg_bar, width = 10, height = 8, dpi = 600)
```


### GO 
```{r, fig.width=15}
if(!dir.exists("../../Result/Enrichment")){
  dir.create("../../Result/Enrichment", recursive = T)
}
GO_gsea <- get_fgsea(pathways = pathways_hallmark_GO)
saveRDS(GO_gsea, "../../Result/Enrichment/GO_pathway_gsea.RDS")
write.csv(GO_gsea$pgene, "../../Result/Enrichment/GO_pathway_gsea_gene.csv", row.names = F)

# plot per pathway 
if(!dir.exists("../../Result/figure/GO")){
  dir.create("../../Result/figure/GO", recursive = T)
}

GO_POSITIVE_REGULATION_OF_VIRAL_TRANSCRIPTION_pl <- 
  get_es_plot(dataset=GO_gsea, pathways=pathways_hallmark_GO,
         pathway_name="GO_POSITIVE_REGULATION_OF_VIRAL_TRANSCRIPTION")
GO_POSITIVE_REGULATION_OF_VIRAL_TRANSCRIPTION_pl
ggsave("../../Result/figure/GO/GO_POSITIVE_REGULATION_OF_VIRAL_TRANSCRIPTION.pdf",
       GO_POSITIVE_REGULATION_OF_VIRAL_TRANSCRIPTION_pl, width = 5, height = 4, dpi = 600)

# top pathway
GO_bar <- get_plot(dataset=GO_gsea, pathways=pathways_hallmark_GO, number=10, tag="GO")
GO_bar
ggsave("../../Result/figure/GO/GO_barplot.pdf", GO_bar, width = 15, height = 8, dpi = 600)
```


### version
```{r}
sessionInfo()
```


### Reference 

1. [Fast Gene Set Enrichment Analysis](https://bioconductor.org/packages/release/bioc/manuals/fgsea/man/fgsea.pdf) 

2. [DESeq results to pathways in 60 Seconds with the fgsea package](https://stephenturner.github.io/deseq-to-fgsea/)

