---
title: "Summarise all the data"
date: "Created: 2021-04-22; updated: `r Sys.Date()`"
author: 
  - name: "Hua Zou"
    email: "zouhua1@outlook.com"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(stringr)
library(data.table)

# rm(list = ls())
options(stringsAsFactors = F)
options(future.globals.maxSize = 1000 * 1024^2)
```


### load phenotype
```{r}
survival_data <- fread("../../Result/phenotype/common_survival_data.tsv")
```


### clinical parameters
```{r}
get_clinical <- function(x){
  
  x <- survival_data
  
  dat_clin <- x
  # pathologic_T 
  dat_clin$Te1 <- str_extract(dat_clin$TNM, "T\\d[a-z]+")
  dat_clin$Te2 <- str_extract(dat_clin$TNM, "T\\d")
  dat_clin$Te1 <- with(dat_clin, ifelse(is.na(Te1), Te2, Te1))
  # table(dat_clin$Te1)
  # table(dat_clin$Te2)
  dat_clin$Te2[dat_clin$Te2 == "T1"] <- "T1-T2"
  dat_clin$Te2[dat_clin$Te2 == "T2"] <- "T1-T2"
  dat_clin$Te2[dat_clin$Te2 == "T3"] <- "T1-T2"
  dat_clin$Te2[dat_clin$Te2 == "T4"] <- "T3-T4"
  Te2 <- table(dat_clin$Te2)
  
  # pathologic_N
  dat_clin$N <- str_extract(dat_clin$TNM, "N\\d")
  dat_clin$N <- str_extract(dat_clin$N, "\\d")
  # table(dat_clin$N)
  
  dat_clin$N[dat_clin$N == "0"] <- "NO"
  dat_clin$N[dat_clin$N == "1"] <- "Yes"
  dat_clin$N[dat_clin$N == "2"] <- "Yes"
  dat_clin$N[dat_clin$N == "3"] <- "Yes"
  N <- table(dat_clin$N)
  
  # pathologic_M
  dat_clin$M <- str_extract(dat_clin$TNM, "M\\d")
  dat_clin$M <- str_extract(dat_clin$M, "\\d")
  # table(dat_clin$M)
  
  dat_clin$M[dat_clin$M == "0"] <- "NO"
  dat_clin$M[dat_clin$M == "1"] <- "Yes"
  M <- table(dat_clin$M)
  
  # Age
  dat_clin$Age <- ifelse(dat_clin$Age > 60, "old", "young")
  Age <- table(dat_clin$Age)
  
  # Gender
  dat_clin$Gender <- ifelse(dat_clin$Gender == "MALE", "Male", "Female")
  Gender <- table(dat_clin$Gender)
  
  # stage
  dat_clin$Stage1 <- str_trim(str_extract(dat_clin$Stage, "\\s[H-Z]+"),
                              side = c("both", "left", "right"))
  # table(dat_clin$Stage1)
  dat_clin$Stage1[dat_clin$Stage1 == "I"] <- "Stage I-II"
  dat_clin$Stage1[dat_clin$Stage1 == "II"] <- "Stage I-II"
  dat_clin$Stage1[dat_clin$Stage1 == "III"] <- "Stage III-IV"
  dat_clin$Stage1[dat_clin$Stage1 == "IV"] <- "Stage III-IV"
  Stage <- table(dat_clin$Stage1)
  
  dat_cal <- data.frame(Clinicopathological=c(
                          rep("Age", length(Age)),
                          rep("Gender", length(Gender)),
                          rep("Stage", length(Stage)),
                          rep("T", length(Te2)),
                          rep("N", length(N)),
                          rep("M", length(M))), 
                        Name = c(names(Age), names(Gender), 
                                 names(Stage), names(Te2),
                                 names(N), names(M)),
                        Number = c(as.numeric(Age), as.numeric(Gender), 
                                 as.numeric(Stage), as.numeric(Te2),
                                 as.numeric(N), as.numeric(M)),
                        Rate = c(as.numeric(Age)/nrow(x),
                                 as.numeric(Gender)/nrow(x),
                                 as.numeric(Stage)/nrow(x),
                                 as.numeric(Te2)/nrow(x),
                                 as.numeric(N)/nrow(x),
                                 as.numeric(M)/nrow(x))
                        )
  return(dat_cal)  
}

# calculate 
clin_sum <- get_clinical(survival_data)
DT::datatable(clin_sum)

# Age
paste(mean(survival_data$Age), sd(survival_data$Age), sep = " +/- ")
```


### Multi-Omics Data status
```{r}
copyNumber <- fread("../../Result/profile/copyNumber_filter.tsv")
geneExp <- fread("../../Result/profile/geneExp_filter.tsv")
methylation <- fread("../../Result/profile/methylation_filter.tsv")
protein_RPPA <- fread("../../Result/profile/protein_RPPA_filter.tsv")

dim(copyNumber)
dim(geneExp)
dim(methylation)
dim(protein_RPPA)
```



```{r}

```

### version
```{r}
sessionInfo()
```


### Reference 

1. [解决生存分析和临床参数相关分析](https://www.jianshu.com/p/9cc986dcf285)

2. [怎么处理生存时间为0的样本](https://www.biostars.org/p/153013/)

