---
title: "autoencoder"
date: "Created: 2021-01-08; updated: `r Sys.Date()`"
author: 
  - name: "Hua Zou"
    email: "zouhua1@outlook.com"
output: 
  html_notebook:
    codes: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr)
library(tibble)
library(data.table)

rm(list = ls())
options(stringsAsFactors = F)
options(future.globals.maxSize = 1000 * 1024^2)
```


### old version by PanXingXin
```{r}
Before_Autoencoder_prf <- fread("../../Result/profile/PanXingxin/matrix.txt")
Autoencoder_features <- fread("../../Result/profile/PanXingxin/transform_matrix.csv")

rownames(Autoencoder_features) <- Before_Autoencoder_prf$sample
colnames(Autoencoder_features) <- paste0("AE_Feature_", c(1:100))

write.csv(Autoencoder_features, "../../Result/profile/PanXingxin/Autoencoder_features_profile.csv", 
          row.names = T)
```


### load data 
```{r}
phen <- fread("../../Result/phenotype/common_survival_data.tsv")

copyNumber <- fread("../../Result/profile/copyNumber_filter.tsv")
geneExp <- fread("../../Result/profile/geneExp_filter.tsv")
methylation <- fread("../../Result/profile/methylation_filter.tsv")
protein_RPPA <- fread("../../Result/profile/protein_RPPA_filter.tsv")
```


### deal with data for the input data of autoencoder(relabel the features)
```{r}
copyNumber_cln <- copyNumber %>% mutate(Type="copyNumber") %>%
  mutate(Name=paste(V1, Type, sep = "_")) %>%
  dplyr::select(Name, V1, Type, everything()) %>%
  dplyr::select(-c("V1", "Type")) %>%
  column_to_rownames("Name") %>%
  t() %>% data.frame() %>%
  rownames_to_column("SampleID")

geneExp_cln <- geneExp %>% mutate(Type="geneExp") %>%
  mutate(Name=paste(V1, Type, sep = "_")) %>%
  dplyr::select(Name, V1, Type, everything()) %>%
  dplyr::select(-c("V1", "Type")) %>%
  column_to_rownames("Name") %>%
  t() %>% data.frame() %>%
  rownames_to_column("SampleID")

methylation_cln <- methylation %>% mutate(Type="methylation") %>%
  mutate(Name=paste(V1, Type, sep = "_")) %>%
  dplyr::select(Name, V1, Type, everything()) %>%
  dplyr::select(-c("V1", "Type")) %>%
  column_to_rownames("Name") %>%
  t() %>% data.frame() %>%
  rownames_to_column("SampleID")

protein_RPPA_cln <- protein_RPPA %>% mutate(Type="protein_RPPA") %>%
  mutate(Name=paste(V1, Type, sep = "_")) %>%
  dplyr::select(Name, V1, Type, everything()) %>%
  dplyr::select(-c("V1", "Type")) %>%
  column_to_rownames("Name") %>%
  t() %>% data.frame() %>%
  rownames_to_column("SampleID")

require(plyr)
mdat <- join_all(list(copyNumber_cln, geneExp_cln, 
                      methylation_cln, protein_RPPA_cln), 
                 by='SampleID', type='left') 
```


### output 
```{r}
dir_prf <- "../../Result/profile"
if(!dir.exists(dir_prf)){
  dir.create(dir_prf)
}

# mdat
mdat.path <- paste(dir_prf, "All_filter_merge_profile.tsv", sep = "/")
fwrite(mdat, file = mdat.path, quote = F, sep = "\t")
```


### Autoencoder script
```{python}
from keras.models import Model
from keras.layers import Input, Dense, Flatten, Add, Lambda, LeakyReLU, Embedding
from keras.layers import Dropout, Conv1D, MaxPooling1D, AveragePooling1D, GlobalAveragePooling1D, SpatialDropout1D
from keras.layers import GRU, Activation, Bidirectional, LSTM, concatenate, BatchNormalization
from keras.optimizers import SGD, Adam
from functools import partial
from bayes_opt import BayesianOptimization
import keras.metrics as km
from keras.utils import plot_model
from sklearn.model_selection import train_test_split
from keras.layers.recurrent import LSTM
from keras.layers.wrappers import TimeDistributed
from keras import regularizers
from keras import initializers
from keras import constraints
from keras import backend as K
from keras.engine import Layer, InputSpec
from keras.metrics import binary_accuracy
from keras.initializers import Ones, Zeros
import tensorflow as tf
from keras.layers import Embedding
from keras.utils.generic_utils import get_custom_objects
from keras.callbacks import EarlyStopping
import numpy as np
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.constraints import maxnorm
import json
from keras.callbacks import ModelCheckpoint
import json
import time
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from matplotlib import pyplot
from keras.models import load_model 

mat = pd.read_csv("All_filter_merge_profile.tsv", header=0, sep="\t", index_col="SampleID")
matrix = mat.to_numpy()

X_train, X_test = train_test_split(matrix, test_size=0.2, random_state=1)

t = MinMaxScaler()
t.fit(X_train)
X_train = t.transform(X_train)
X_test = t.transform(X_test)
n_inputs = matrix.shape[1]

visible = Input(shape=(n_inputs,))
e = Dense(1000)(visible)
e = BatchNormalization()(e)
e = Activation('tanh')(e)

n_bottleneck = 100
bottleneck = Dense(n_bottleneck)(e)

d = Dense(1000)(bottleneck)
d = BatchNormalization()(d)
d = Activation('tanh')(d)

output = Dense(n_inputs, activation='tanh')(d)

model = Model(inputs=visible, outputs=output)

model.compile(optimizer='adam', loss='binary_crossentropy')

plot_model(model, './autoencoder.png', show_shapes=True)

es = EarlyStopping(monitor='val_loss', verbose=1, patience=25,mode="auto",)

mc = ModelCheckpoint('autoencoder.h5', monitor='val_loss', mode="auto",verbose=1, save_best_only=True)


history = model.fit(X_train, X_train, epochs=300, batch_size=32, verbose=2, validation_data=(X_test,X_test), callbacks=[es,mc])
# plot loss
pyplot.plot(history.history['loss'], label='train')
pyplot.plot(history.history['val_loss'], label='test')
pyplot.legend()

pyplot.savefig('history.png')
pyplot.show()

encoder = Model(inputs=visible, outputs=bottleneck)
plot_model(encoder, 'encoder.png', show_shapes=True)

encoder.save('encoder.h5')

encoder = load_model('encoder.h5')

transform_matrix = encoder.predict(matrix)

np.savetxt("Autoencoder_top100_features.csv", transform_matrix, delimiter=",")
```


### add colnames and rownames to features profile table 
```{r}
Before_Autoencoder_prf <- fread("../../Result/profile/All_filter_merge_profile.tsv")
Autoencoder_features <- fread("../../Result/profile/Autoencoder_top100_features.csv")

rownames(Autoencoder_features) <- Before_Autoencoder_prf$SampleID
colnames(Autoencoder_features) <- paste0("Feature", formatC(seq(1:100), width = 3, flag=0))

write.csv(Autoencoder_features %>% rownames_to_column("SampleID"),
          "../../Result/profile/Autoencoder_top100_newfeatures.csv", row.names = F)
```


### version
```{r}
sessionInfo()
```
